config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
	root to: 'tasks#index'
	resources :tasks
	resources :users, only: [:new, :create, :show, :update, :edit]
	resources :sessions, only: [:new, :create, :destroy]
	namespace :admin do
		resources :users
	end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/label.rb
class Label < ApplicationRecord
	has_many :labellings, dependent: :destroy
	has_many :tasks, through: :labellings
end

app/models/labelling.rb
class Labelling < ApplicationRecord
	belongs_to :task
	belongs_to :label
end

app/models/task.rb
class Task < ApplicationRecord
	validates :task_name, presence: true
	scope :task_name_search, -> (query) {where("task_name LIKE ?", "%#{query}%")}
	def task_name_search(query)
	  where("task_name LIKE ?", "%#{query}%")
	end

	scope :status_search, -> (query) {where(status: query)}
	def status_search(query)
	  where(status: query)
	end

	scope :user_task_list, -> (query) {where(user_id: query)}
	def user_task_list(query)
	  where(user_id: query)
	end

	scope :label_task_search, -> (query) {
		@ids = Labelling.where(label_id: query).pluck(:task_id)
		where(id: @ids)}

	scope :priority_ordered, -> {order("
	    CASE tasks.priority 
	    WHEN 'high' THEN 'a' 
	    WHEN 'medium' THEN 'b' 
	    WHEN 'low' THEN 'c' 
	    ELSE 'z' 
	    END ASC, 
	    id DESC" )}
	max_paginates_per 5
	belongs_to :user
	has_many :labellings, dependent: :destroy
	has_many :labels, through: :labellings
end

app/models/user.rb
class User < ApplicationRecord
	validates :name,  presence: true, length: { maximum: 30 }
	validates :email, presence: true, length: { maximum: 255 },format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
	before_validation { email.downcase! }
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }
	has_many :tasks, dependent: :destroy
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
	skip_before_action :login_required, only: [:edit, :update, :destroy, :show]
	before_action :is_admin, only: [:edit, :update, :destroy, :show,:index, :new]
	before_action :set_user, only: [:edit, :update, :destroy, :show]
	
	def index
		@users = User.select(:id, :name, :admin)
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
		  	redirect_to admin_users_path
		else
		  	render :new
		end
	end

	def edit
	end

	def update
		if params[:admin]
			if @user.admin == true
				@user.update_attribute(:admin, false)
			else
				@user.update_attribute(:admin, true)
			end
		else
			if @user.update(user_params)
			    redirect_to admin_users_path, notice: "Profil edited!"
			else
			    render :edit
			end
		end
	end

	def show
	end

	def destroy
		@user.destroy
		redirect_to admin_users_path, notice:"User deleted!"
	end

	private

	def user_params
		params.require(:user).permit(:name, :email, :password,
	                          	 :password_confirmation)
	end

	def set_user
		@user = User.find(params[:id])
	end

	def is_admin
		if current_user.admin == false || current_user.admin.blank?
			redirect_to tasks_path, notice:"Only administrators can access this page!!"
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	include SessionsHelper
	before_action :login_required

	private

	def login_required
		redirect_to new_session_path unless current_user
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to tasks_path()
    else
      flash.now[:danger] = 'I failed to login'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash.now[:notice] = 'Deconnected'
    redirect_to new_session_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	before_action :set_task, only: [:edit, :update, :show, :destroy]
	def index
		all_tasks= Task.user_task_list(current_user.id)
		if params[:sort_expired]
			@tasks = all_tasks.order('deadline DESC').page params[:page]
		elsif params[:task_name].present?
			if params[:status].present?
				@tasks = all_tasks.task_name_search(params[:task_name]).status_search(params[:status]).page params[:page]
			else
				@tasks = all_tasks.task_name_search(params[:task_name]).page params[:page]
			end
		elsif params[:status].present?
			@tasks = all_tasks.status_search(params[:status]).page params[:page]
		elsif params[:label_id].present?
			@tasks = all_tasks.label_task_search(params[:label_id]).page params[:page]
		elsif params[:sort_priority]
			@tasks = all_tasks.priority_ordered.page params[:page]
		else
			@tasks = all_tasks.order('created_at DESC').page params[:page]
		end
	end

	def new
		@task = Task.new
	end

	def create
		@task = current_user.tasks.build(task_params)
		if params[:back]
	  		render :new
		else
			if @task.save
				redirect_to tasks_path, notice: "task created!"
			else
				render :new
			end
		end
	end


	def edit
	end

	def update
		if @task.update(task_params)
	  		redirect_to tasks_path, notice: "task edited!"
		else
	  		render :edit
		end
	end

	def show
	end

	def destroy
		@task.destroy
		redirect_to tasks_path, notice:"task deleted!"
	end

	private

	def task_params
		params.require(:task).permit(:task_name,:description,:status, :priority, :deadline, label_ids: [])
	end

	def set_task
		@task = Task.find(params[:id])
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create, :edit, :update, :show]

  def new
  	if logged_in?
  		redirect_to tasks_path
  	else
    	@user = User.new
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
    	session[:user_id] = @user.id
      	redirect_to tasks_path
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
    if current_user.id != @user.id
  		redirect_to tasks_path
  	end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
        redirect_to user_path(@user.id), notice: "Profil edited!"
    else
        render :edit
    end
  end
  
  def show
  	@user = User.find(params[:id])
  	if current_user.id != @user.id
  		redirect_to tasks_path
  	end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                              	 :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
	@current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
	current_user.present?
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<h1>Edit the user</h1>
<div class="form">
  <%= form_with(model: @user, local: true, url: admin_user_path) do |f| %>
    <% if @user.errors.any? %> 
      <div id="error_explanation"> 
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2> 
        <ul> 
          <% @user.errors.full_messages.each do |message| %> 
            <li><%= message %></li> 
          <% end %> 
        </ul> 
      </div>
    <% end %>
    <br>
    <%= f.text_field :name, placeholder: "Name..." %> 
    <br>
    <br>
    <%= f.email_field :email, placeholder: "Email..." %>
    <br>
    <br> 
    <%= f.password_field :password, placeholder: "Password..." %>
    <br> 
    <br> 
    <%= f.password_field :password_confirmation, placeholder: "Password confirmation..." %> 
    <br>
    <br>
    <%= f.submit "Create my account", class: "submit" %> 
  <% end %>
</div>

app/views/admin/users/index.html.erb
<h2>Users list</h2>
<% @users.each do |user| %>
	<p> <%= user.id %> : <%= user.name %>, Tasks created: <%= user.tasks.count %> ,
		<% if user.admin == true %>
			Role: Admin <%= link_to 'Unset admin', admin_user_path(user.id, admin: "true"), method: :patch %>
		<% else %>
			Role: No Admin <%= link_to 'Set admin', admin_user_path(user.id, admin: "true"), method: :patch %>
		<% end %>
		<% @id = user.id%>
		<%= link_to "Modifier", edit_admin_user_path(user.id) %> <%= link_to 'Supprimer', admin_user_path(user.id), method: :delete ,id: "delete#{@id}"%> <%= link_to 'Show', admin_user_path(user.id) %> 
</p>
<% end %>

app/views/admin/users/new.html.erb
<h1>Admin creates a user</h1> 


<div class="form">
  <%= form_with(model: @user, local: true, url: admin_users_path) do |f| %>
    <% if @user.errors.any? %> 
      <div id="error_explanation"> 
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2> 
        <ul> 
          <% @user.errors.full_messages.each do |message| %> 
            <li><%= message %></li> 
          <% end %> 
        </ul> 
      </div>
    <% end %>
    <br>
    <%= f.text_field :name, id: "name", placeholder: "Name..." %> 
    <br>
    <br>
    <%= f.email_field :email, id: "email", placeholder: "Email..." %>
    <br>
    <br> 
    <%= f.password_field :password, id: "password", placeholder: "Password..." %>
    <br> 
    <br> 
    <%= f.password_field :password_confirmation, id: "password_confirmation", placeholder: "Password confirmation..." %> 
    <br>
    <br>
    <%= f.submit "Create account", class: "submit", value: "Register" %> 
  <% end %>
</div>

app/views/admin/users/show.html.erb
<h1>Tasks of <%= @user.name %></h1>

<table class="table table-hover">
  <thead>
  <tr>
    <th scope="col">Task Name</th>
    <th scope="col">Description</th>
    <th scope="col">Priority</th>
    <th scope="col">Status</th>
    <th scope="col">Deadline</th>
  </tr>
</thead>
<tbody>
<% @user.tasks.each do |task| %>
  <tr >
    <td class="task_row" scope="row"><%= task.task_name %></td>
    <td><%= task.description %></td>
    <td class="priority_row"><%= task.priority %></td>
    <td><%= task.status %></td>
    <td class="deadline_row"><%= task.deadline %></td>
  </tr>
<% end %>
</tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Everleaf</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
          <% if logged_in? %>
            <div class="menu">
            <i class="fas fa-home"></i> <%= link_to "Home", tasks_path,  class: "link" %> |
            <%= link_to 'New task', new_task_path, class: "link" %> |
            <%= link_to 'Change profil', edit_user_path(current_user.id), class: "link" %> |
            <%= link_to 'My page', user_path(current_user.id), class: "link" %> |
            <%= link_to "Logout", session_path(current_user.id), method: :delete %>
          <% else %>
            <%= link_to "Sign up", new_user_path %> |
            <%= link_to "Login", new_session_path %>
          </div>
          <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: @task, local: true ) do |form| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= @task.errors.count %>Something wrong</h2>
      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <div class="form">  
  <div class="task_title form-group">
    <%= form.label :Task_name %>
    <%= form.text_field :task_name, id: "task" , class: "form-control"%>
  </div>
  
  <div class="task_title form-group">
    <%= form.label :Description %>
    <%= form.text_field :description, class: "form-control" %>
  </div>
 
  <div class="task_title form-group">
    <%= form.label :Priotity %>
    <%= form.select :priority, options_for_select([[''],['high'], ['medium'], ['low']]), id: "priority", class: "form-control"  %>
  </div>
   <div class="task_title form-group">
    <%= form.label :Status %>
    <%= form.select :status, options_for_select([[''],['unstarted'], ['in progress'], ['completed']]), id: "status", class: "form-control"  %>
  </div>
  
  <div class="task_title form-group">
    <%= form.label :Deadline %>
    <%= form.date_select :deadline, id: "deadline", class: "form-control"%>
  </div>

  <% Label.all.each do |label| %>
    <%= form.check_box :label_ids, { multiple: true, checked: label[:checked], disabled: label[:disabled], include_hidden: false }, label[:id] %>
    <%= form.label :label_ids, label.title, value: "#{label.id}" %>
  <% end %>
  <%= form.submit value:"Register", class: "btn btn-primary submit"%>
</div>
<% end %>
<br>
<%= link_to "Back to the task list", tasks_path, class: "badge badge-success" %>

app/views/tasks/edit.html.erb
<h2>Edit Task</h2>
<%= render 'form' %>

app/views/tasks/index.html.erb
<h1>Tasks index</h1>
<p><%= notice %></p>
<nav class="navbar navbar-light bg-light">
<%= form_with url: tasks_path, method: :get, html: {class: "form-inline"} , local: true do |form| %>
  <%= form.label :task_name, "Task name:" %>
  <%= form.text_field :task_name, class: "form-control mr-sm-2" %>
  <%= form.label :status, "Status:" %>
  <%= form.select :status, options_for_select([[''],['unstarted'], ['in progress'], ['completed']]), class: "form-control mr-sm-2"%>
  <%= form.label :label_id, "Only Label search:" %>
  <%= form.select :label_id, Label.all.collect { |l| [ l.title, l.id ] }, include_blank: true %>
  <%= form.submit value: "search", class: "btn btn-outline-success my-2 my-sm-0", type: "submit" %>
<% end %>
</nav>
<br>
<p><%= link_to "sort by end deadline", tasks_path(sort_expired: "true") , value: "dater", class: "badge badge-primary"%> ||
  <%= link_to "sort by priority", tasks_path(sort_priority: "true"), class: "badge badge-success" %>
</p>
<table class="table table-hover">
  <thead>
  <tr>
    <th scope="col">Task Name</th>
    <th scope="col">Description</th>
    <th scope="col">Priority</th>
    <th scope="col">Status</th>
    <th scope="col">Deadline</th>
  </tr>
</thead>
<tbody>
<% @tasks.each do |task| %>
  <tr >
    <td class="task_row" scope="row"><%= task.task_name %></td>
    <td><%= task.description %></td>
    <td class="priority_row"><%= task.priority %></td>
    <td><%= task.status %></td>
    <td class="deadline_row"><%= task.deadline %></td>
    <td><%= link_to 'See details', task_path(task.id) %></td>
    <td><%= link_to "Modifier", edit_task_path(task.id) %></td>
    <td><%= link_to 'Supprimer', task_path(task.id), method: :delete %></td>
  </tr>
<% end %>
</tbody>
</table>

<br>

<%= link_to 'Create a new task', new_task_path, class: "badge badge-success" %> || <%= paginate @tasks %>

app/views/tasks/new.html.erb
<h2>Create Task</h2>
<%= render 'form' %>

app/views/tasks/show.html.erb
<h1>Task details</h1>
<p>Name: <%= @task.task_name %></p>
<p>Description: <%= @task.description %></p>
<p>Priority: <%= @task.priority %></p>
<p>Status: <%= @task.status %></p>
<p>Deadline: <%= @task.deadline %></p>
<h3>List of label associated with the task</h3>
<% @task.labels.pluck(:title).each do |task_label| %>
	<p> <%= task_label %> </p>
<% end %>

app/views/users/edit.html.erb
<%= form_with(model: @user, local: true ) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= @user.errors.count %>Something wrong</h2>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <br>
  <div class="user">
    <p>Change Profile?</p>
    <div class="form">
        <br>
        <%=form.label :Name %>
        <%= form.text_field :name, placeholder: "Name..." %> 
        <br>
        <br>
        <%=form.label :Email %>
        <%= form.email_field :email, placeholder: "Email..." %>
        <br>
        <br>
        <%= form.password_field :password, placeholder: "Password..." %>
        <br> 
        <br> 
        <%= form.password_field :password_confirmation, placeholder: "Password confirmation..." %>
        <br>
        <br>
    </div>
    <br>
    <%= form.submit "Update", class: "submit" %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1> 

<div class="form">
  <%= form_with(model: @user, local: true) do |f| %>
    <% if @user.errors.any? %> 
      <div id="error_explanation"> 
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2> 
        <ul> 
          <% @user.errors.full_messages.each do |message| %> 
            <li><%= message %></li> 
          <% end %> 
        </ul> 
      </div>
    <% end %>
    
    <br>
    <%= f.text_field :name, id: "name", placeholder: "Name..." %> 
    <br>
    <br>
    <%= f.email_field :email, id: "email", placeholder: "Email..." %>
    <br>
    <br> 
    <%= f.password_field :password, id: "password", placeholder: "Password..." %>
    <br> 
    <br> 
    <%= f.password_field :password_confirmation, id: "password_confirmation", placeholder: "Password confirmation..." %> 
    <br>
    <br>
    <%= f.submit "Create my account", class: "submit", value: "Register" %> 
  <% end %>
</div>

app/views/users/show.html.erb
<h1>Welcome to your page <%= @user.name %></h1>
<p>E-mail address: <%= @user.email %></p>